language: ruby
cache: bundler
sudo: false

rvm:
  - 2.4.1

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.0.x.sprockets-4.x

matrix:
  exclude:
    - gemfile: Gemfile
      rvm: 1.9.3
    - gemfile: Gemfile
      rvm: 2.0.0
    - gemfile: Gemfile
      rvm: 2.1
    - gemfile: gemfiles/Gemfile.rails-5.0.x
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.rails-5.0.x
      rvm: 2.0.0
    - gemfile: gemfiles/Gemfile.rails-5.0.x
      rvm: 2.1
    - gemfile: gemfiles/Gemfile.rails-5.0.x.sprockets-4.x
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.rails-5.0.x.sprockets-4.x
      rvm: 2.0.0
    - gemfile: gemfiles/Gemfile.rails-5.0.x.sprockets-4.x
      rvm: 2.1
